{{- if .Values.affine.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "affine.fullname" . }}-storage
  labels:
    {{- include "affine.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.affine.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.affine.persistence.size | quote }}
  {{- if .Values.affine.persistence.storageClassName }}
  storageClassName: {{ .Values.affine.persistence.storageClassName }}
  {{- end }}
  {{- if .Values.affine.persistence.existingClaim }}
  volumeName: {{ .Values.affine.persistence.existingClaim }}
  {{- end }}
---
{{- end }}
{{- if .Values.affine.configPersistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "affine.fullname" . }}-config
  labels:
    {{- include "affine.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.affine.configPersistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.affine.configPersistence.size | quote }}
  {{- if .Values.affine.configPersistence.storageClassName }}
  storageClassName: {{ .Values.affine.configPersistence.storageClassName }}
  {{- end }}
  {{- if .Values.affine.configPersistence.existingClaim }}
  volumeName: {{ .Values.affine.configPersistence.existingClaim }}
  {{- end }}
{{- end }} 