name: Lint and Test Charts

on:
  pull_request:
    paths:
      - "affine/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: "latest"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart linting
        run: ct lint --target-branch main --config ct.yaml

      - name: Run chart testing (install)
        run: ct install --target-branch main --config ct.yaml
