name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Required for the semantic-release/git plugin to push changes
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # yq is needed for the prepareCmd in .releaserc.json
      - name: Install yq
        run: sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic # Add an ID to reference outputs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add any other necessary tokens like NPM_TOKEN if publishing elsewhere

      - name: Set up Helm
        uses: azure/setup-helm@v4
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Add Helm repo dependencies
        run: helm repo add bitnami https://charts.bitnami.com/bitnami
        if: steps.semantic.outputs.new_release_published == 'true'

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        if: steps.semantic.outputs.new_release_published == 'true'
        with:
          skip_existing: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
